### ISSUE TITLE
Fails to install under Mountain Lion

### ISSUE THREAD

**Issue by LDMartin1959** [iKenndac/500px-Aperture-Uploader#25]
Attempt to install returns the following error: "Install 500px Aperture Uploader? can't be opended bacuase it is from an unidentified developer.

**Comment by tmjbradley** [comment]
Mountain Lion includes GateKeeper to offer more security, the default GateKeeper setting is to only allow applications from the Mac App Store or signed but registered developers to be installed. The best option is to bypass GateKeeper for this app:
- Right-click (or control-click) on the installer
- Choose "Open"
- It should pop up the same error message but this time with the option of bypassing GateKeeper and completing the install.

**Comment by scan666** [comment]
I'm getting the same issue. Its not GateKeeper as I have it disabled. Here is the error message

The installation failed with the following error: Error Domain=NSCocoaErrorDomain Code=513 "“500px Aperture Uploader.ApertureExport” couldn’t be copied because you don’t have permission to access “Export”." UserInfo=0x7fe453892e40 {NSSourceFilePathErrorKey=/Users/**_User**_/Desktop/Install 500px Aperture Uploader.app/Contents/Resources/500px Aperture Uploader.ApertureExport, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/**_User**_/Library/Application Support/Aperture/Plug-Ins/Export/500px Aperture Uploader.ApertureExport, NSFilePath=/Users/**_User**_/Desktop/Install 500px Aperture Uploader.app/Contents/Resources/500px Aperture Uploader.ApertureExport, NSUnderlyingError=0x7fe4538935f0 "The operation couldn’t be completed. Permission denied"}

**Comment by iKenndac** [comment]
Looks like you don't have permissions to access parts of your own home folder, which might still be a GateKeeper problem even though it's "disabled", permissions are still stricter in ML.

To install, navigate to `/Users/$USER_NAME/Library/Application Support/Aperture/Plug-Ins/Export/`, creating any missing folders along the way. Then, right-click on the 500px Installer, choose "Show Package Contents" then go to "Contents" then "Resources" folders. In there, you'll find the Aperture plugin — drag that the to "Export" folder you just created or navigated to and you'll be set.

**Comment by scan666** [comment]
Thank you so much for your prompt response, and for the plugin itself. You were absolutely right, for some reason inside Application Support/Aperture/ the Plug-Ins and Export folders were both down as "system" permission granted. I changed the permissions and ran the installer again and naturally it worked as it should.

Thanks again!

**Comment by iKenndac** [comment]
Aha, ok. Would you mind creating a new issue about this, including the error you pasted above? The installer should be smarter about dealing with stuff like this.

**Comment by scan666** [comment]
Sure
